version: "3"
name: "hackathon"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
